- name: "HTH | Kitty | Set branch"
  ansible.builtin.set_fact:
    kitty_branch: "{{ 'nightly' if(version == 'nightly') else 'v' + version }}"

- name: "HTH | Kitty | Set version install path"
  ansible.builtin.set_fact:
    kitty_version_path: "{{ hth_default_kitty_linux_installation_path }}/{{ version }}"

- name: " HTH | Kitty | Lookup version executable"
  ansible.builtin.stat:
    path:  "{{ kitty_version_path }}/bin/kitty"
  register: kitty_version_executable

- name: "HTH | Kitty | Set artifact format"
  ansible.builtin.set_fact:
    kitty_artifact_ending: "{{ 'txz' if(ansible_system == 'Linux') else 'dmg' }}"

- name: "HTH | Kitty | Set version archive name"
  ansible.builtin.set_fact:
    kitty_archive_name: "kitty-{{ version }}{{ '-' + kitty_architecture if(kitty_architecture | length > 0) else '' }}.{{ kitty_artifact_ending }}"
  when:
    - not kitty_version_executable.stat.exists

- name: "HTH | Kitty | Set version archive download path"
  ansible.builtin.set_fact:
    kitty_archive_download_path: "/tmp/{{ kitty_archive_name }}"
  when:
    - not kitty_version_executable.stat.exists

- block:
  - name: "HTH | Kitty | Download version archive"
    ansible.builtin.get_url:
      url: "https://github.com/kovidgoyal/kitty/releases/download/{{ kitty_branch }}/{{ kitty_archive_name }}"
      dest: "{{ kitty_archive_download_path }}"
      #checksum: "{{ checksum }}"
    register: archive_download_state
    when:
      - not kitty_version_executable.stat.exists

  - name: "HTH | Kitty | Extract version archive"
    ansible.builtin.include_tasks: extract/main.yml
    when:
      - not kitty_version_executable.stat.exists

  always:

    - name: "HTH | Kitty | Cleanup temporary files"
      ansible.builtin.file:
        path: "{{ kitty_archive_download_path }}"
        state: absent
      when:
        - archive_download_state is defined
        - archive_download_state.changed
