- name: "HTH | Kitty | Assert input variables"
  ansible.utils.validate:
    data: "{{ kitty }}"
    criteria: "{{ lookup('file', 'criteria/kitty.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost

- name: "HTH | Kitty | Map Linux architecture to artifact architecture"
  ansible.builtin.set_fact:
    kitty_architecture: >-
      {{
        hth_kitty_default_os_linux_architecture_map
        | dict2items
        | selectattr('value', 'contains', ansible_architecture)
        | map(attribute='key')
        | first | default(none)
      }}
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'

- name: "HTH | Kitty | Validate Linux OS architecture compatibility"
  ansible.builtin.fail:
    msg: "No valid architecture mapping found for '{{ ansible_architecture }}'! See default values in README for adding a new mapping."
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'
    - kitty_architecture | length == 0

- name: "HTH | Kitty | Fetch latest version number"
  ansible.builtin.uri:
    url: "{{ hth_default_kitty_latest_version_url }}"
    return_content: yes
  register: kitty_latest_version_result
  when:
    - kitty.remove is undefined or not kitty.remove
    - (kitty.stable is defined and kitty.stable.version == 'latest') or (kitty.default is defined and kitty.default.version == 'latest')

- name: "HTH | Kitty | Set latest version"
  ansible.builtin.set_fact:
    kitty_latest_version: "{{ kitty_latest_version_result.content }}"
  when:
    - kitty.remove is undefined or not kitty.remove
    - kitty_latest_version_result is defined

- name: "HTH | Kitty | Set stable version"
  ansible.builtin.set_fact:
    kitty_stable_version: "{{ kitty_latest_version if(kitty.stable.version == 'latest') else kitty.stable.version }}"
  when:
    - kitty.remove is undefined or not kitty.remove
    - kitty.stable is defined

- name: "HTH | Kitty | Download stable artifact"
  ansible.builtin.include_tasks: download.yml
  vars:
    version: "{{ kitty_stable_version }}"
  when:
    - kitty.remove is undefined or not kitty.remove
    - kitty.stable is defined

- name: "HTH | Kitty | Download nightly artifact"
  ansible.builtin.include_tasks: download.yml
  vars:
    version: "nightly"

  when:
    - kitty.remove is undefined or not kitty.remove
    - kitty.nightly is defined
    - kitty.nightly

- name: "HTH | Kitty | Trim versions"
  ansible.builtin.include_tasks: trim.yml
  vars:
    versions: >-
      {{
        [
          ( kitty_stable_version if (kitty.stable is defined) | default(None)),
          ('nightly' if (kitty.nightly | default(false)) else None)
        ] | select('truthy') | list
      }}
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'
    - kitty.trim is defined
    - kitty.trim

- name: "HTH | Kitty | Set default version"
  ansible.builtin.include_tasks: default.yml
  vars:
    version: "{{ 'nightly' if (kitty.default.version == 'nightly') else kitty_latest_version if (kitty.default.version == 'latest') else kitty.default.version }}"
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'
    - kitty.default is defined

- name: "HTH | Kitty | Remove package"
  ansible.builtin.include_tasks: remove.yml
  when:
    - kitty.remove is defined
    - kitty.remove
