- name: "HTH | Kitty | Assert input variables"
  ansible.utils.validate:
    data: "{{ kitty }}"
    criteria: "{{ lookup('file', 'criteria/kitty.json') | from_json }}"
    engine: ansible.utils.jsonschema
  run_once: yes
  delegate_to: localhost

- name: "HTH | Kitty | Set symlink 'kitty' path"
  ansible.builtin.set_fact:
    kitty_absolute_symlink_path: "{{ hth_default_kitty_linux_symlink_path }}/kitty"

- name: "HTH | Kitty | Set symlink 'kitten' path"
  ansible.builtin.set_fact:
    kitten_absolute_symlink_path: "{{ hth_default_kitty_linux_symlink_path }}/kitten"

- name: "HTH | Kitty | Set desktop entry path"
  ansible.builtin.set_fact:
    kitty_desktop_entry_path: "{{ hth_default_kitty_linux_desktop_entry_path }}/kitty.desktop"

- name: "HTH | Kitty | Map Linux architecture to artifact architecture"
  ansible.builtin.set_fact:
    kitty_architecture: >-
      {{
        hth_kitty_default_os_linux_architecture_map
        | dict2items
        | selectattr('value', 'contains', ansible_architecture)
        | map(attribute='key')
        | first | default(none)
      }}
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'

- name: "HTH | Kitty | Validate Linux OS architecture compatibility"
  ansible.builtin.fail:
    msg: "No valid architecture mapping found for '{{ ansible_architecture }}'! See default values in README for adding a new mapping."
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'
    - kitty_architecture | length == 0

- name: "HTH | Kitty | Find releases using 'latest' versions"
  ansible.builtin.set_fact:
    kitty_latest_clients: "{{ kitty.releases | selectattr('version', 'equalto', 'latest') | list }}"
  when:
    - kitty.releases is defined

- name: "HTH | Kitty | Fetch latest version"
  ansible.builtin.include_tasks: latest.yml
  when:
    - kitty_latest_clients is defined
    - (kitty_latest_clients | length > 0) or (kitty.default is defined and kitty.default.version == 'latest')

- name: "HTH | Kitty | Manage releases"
  ansible.builtin.include_tasks: manage/main.yml
  loop: "{{ kitty.releases }}"
  loop_control:
    loop_var: client
  when:
    - kitty.releases is defined

- name: "HTH | Kitty | Remove undefined versions"
  ansible.builtin.include_tasks: trim.yml
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'
    - kitty.trim is defined
    - kitty.trim

- name: "HTH | Kitty | Set default version"
  ansible.builtin.include_tasks: default.yml
  when:
    - kitty.remove is undefined or not kitty.remove
    - ansible_system == 'Linux'
    - kitty.default is defined

- name: "HTH | Kitty | Remove package"
  ansible.builtin.include_tasks: remove.yml
  when:
    - kitty.remove is defined
    - kitty.remove
