---
- name: Verify
  hosts: all
  tasks:

  - name: Load role defaults
    include_vars:
      file: "../../defaults/main.yml"

  - name: Check for version install dir presence
    stat:
      path: "{{ hth_default_kitty_linux_installation_path }}"
    register: kitty_dir_stat

  - name: Check for kitty symlink presence
    stat:
      path: "{{ hth_default_kitty_linux_symlink_path }}/kitty"
    register: kitty_symlink_stat

  - name: Check for kitten symlink presence
    stat:
      path: "{{ hth_default_kitty_linux_symlink_path }}/kitten"
    register: kitty_kitten_symlink_stat

  - name: Check for desktop file presence
    stat:
      path: "{{ hth_default_kitty_linux_desktop_entry_path }}/kitty.desktop"
    register: kitty_desktop_stat

  - name: Fail when install path is found
    fail:
      msg: "Install directory was found!"
    when: kitty_dir_stat.stat.exists

  - name: Fail when kitty is found on path
    fail:
      msg: "'kitty' was found on path!"
    when: kitty_symlink_stat.stat.exists

  - name: Fail when kitten is found on path
    fail:
      msg: "'kitten' was found on path!"
    when: kitty_kitten_symlink_stat.stat.exists

  - name: Fail when desktop entry is found
    fail:
      msg: "Desktop entry was found!"
    when: kitty_desktop_stat.stat.exists
